litigrit_assessment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("llm-adm/", admin.site.urls),
    re_path(
        r"",
        include(
            ("llm.urls", "llm"),
            namespace="llm",
        ),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

llm/urls.py
from django.urls import path

from llm import views

urlpatterns = [
    path(
        "",
        view=views.HomePageView.as_view(),
        name="home",
    ),
    path(
        "login/",
        view=views.LoginPageView.as_view(),
        name="login",
    ),
    path(
        "signup/",
        view=views.SignupPageView.as_view(),
        name="signup",
    ),
    path(
        "logout/",
        view=views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "summary/",
        view=views.SummaryAPIView.as_view(),
        name="summary",
    ),
    path(
        "summary/<uuid:uid>/",
        view=views.SummaryPageView.as_view(),
        name="summary",
    ),
]

llm/models.py
import uuid

from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db.models import (
    PROTECT,
    CharField,
    DateTimeField,
    FileField,
    ForeignKey,
    Model,
    TextField,
    UUIDField,
)

from llm.taxonomies import SummaryLength


class CreateUpdate(Model):
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Summary(CreateUpdate):
    """
    Model representing a summary generated from a PDF file using the
    Gemini API.

    This model stores extracted text from an uploaded PDF, along with
    a summary and metadata related to the summarization process.
    """

    uid = UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for each summary instance.",
    )
    extracted_text = TextField(
        help_text="Extracted text content from the uploaded PDF file."
    )
    attachment = FileField(
        validators=[FileExtensionValidator(["pdf"])],
        help_text="Only PDF files are allowed for processing.",
    )
    title = CharField(
        max_length=255,
        help_text="Title of the document, generated by the Gemini API.",
    )
    summary = TextField(
        help_text="Summarized content of the extracted text, "
        "generated using the Gemini API."
    )
    summary_length = CharField(
        choices=SummaryLength.choices,
        default=SummaryLength.SHORT,
        help_text="Determines the length of the summary "
        "generated from the Gemini API.",
    )
    user = ForeignKey(
        User,
        on_delete=PROTECT,
        blank=True,
        null=True,
        help_text="Reference to the user who generated "
        "the summary (for logged-in users).",
    )
    session_uid = UUIDField(
        blank=True,
        null=True,
        help_text="Session-based identifier for non-logged-in "
        "users, enabling chat history storage.",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Summaries"

llm/forms.py
# App Imports
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import CharField, Form


class LoginForm(Form):
    username = CharField()
    password = CharField()


class SignupForm(Form):
    """
    Validates if password matchs and if the username is unique or not
    """

    username = CharField()
    password = CharField()
    re_password = CharField()

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if password != re_password:
            raise ValidationError(
                {"re_password": "Passwords doesn't match."}, code="invalid"
            )

        user = User(username=username)
        user.validate_unique()
        user.set_password(raw_password=password)
        user.save()
        self.cleaned_data["user"] = user
        return self.cleaned_data

llm/views.py
import uuid

from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.db.models import Case, F, TextField, Value, When
from django.db.models.functions import Concat, Length, Substr
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView
from rest_framework.exceptions import (
    APIException,
)
from rest_framework.exceptions import ValidationError as DRFValidationError
from rest_framework.status import (
    HTTP_200_OK,
)
from rest_framework.views import APIView

from llm.forms import LoginForm, SignupForm
from llm.gemini import GeminiResponseSchema, get_summary_from_google
from llm.mixins import AuthMixin
from llm.models import Summary
from llm.serializers import SummarySerializer
from llm.utils import extract_text_from_pdf


def is_ajax(request) -> bool:
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


class LoginPageView(FormView):
    """
    Form View to log in the user, this uses django template
    """

    form_class = LoginForm
    template_name = "llm/login.html"
    success_url = reverse_lazy("llm:home")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super(LoginPageView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form: LoginForm):
        user = authenticate(
            self.request,
            username=form.cleaned_data.get("username"),
            password=form.cleaned_data.get("password"),
        )
        if not user:
            form.errors.password = ("Invalid login credentials!!",)
            return super(LoginPageView, self).form_invalid(form)
        login(self.request, user)
        self.request.session["uid"] = None
        return redirect(self.success_url)


class SignupPageView(FormView):
    """
    Form View to sign up the user
    """

    form_class = SignupForm
    template_name = "llm/signup.html"
    success_url = reverse_lazy("llm:home")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super(SignupPageView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form: SignupForm):
        login(self.request, form.cleaned_data["user"])
        self.request.session["uid"] = None
        return redirect(self.success_url)


class LogoutView(AuthMixin, TemplateView):
    """
    View to logout the user if logged in
    """

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse_lazy("llm:home"))


class HomePageView(TemplateView):
    template_name = "llm/home.html"

    def get_context_data(self, **kwargs):
        """
        Fetches chat history based on user's login status.

        Reduces the extracted text length to 300 for optimized
        list view using django ORM's annotate
        """
        ctx = super(HomePageView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            filters = dict(user__id=self.request.user.id)
        elif uid := self.request.session.get("uid"):
            filters = dict(session_uid=uid)
        else:
            filters = dict(uid=None)
        ctx["history"] = (
            Summary.objects.filter(**filters)
            .annotate(
                extracted_text_length=Length("extracted_text"),
                short_extracted_text=Case(
                    When(
                        extracted_text_length__gt=300,
                        then=Concat(
                            Substr("extracted_text", 1, 300), Value("...")
                        ),
                    ),
                    default=F("extracted_text"),
                    output_field=TextField(),
                ),
            )
            .values(
                "uid",
                "created",
                "title",
                "summary",
                "short_extracted_text",
                "attachment",
            )
            .order_by("created")
        )
        return ctx


class SummaryAPIView(APIView):
    """
    Summary post using DRF, we can also use FormView but I wanted to showcase
    DRF skills. It assign values to Summary instance which we fetch data
    from gemini and populates user and session_uid.
    """

    def post(self, request, *args, **kwargs):
        try:
            serializer = SummarySerializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            instance: Summary = serializer.save()

            instance.extracted_text = extract_text_from_pdf(
                instance.attachment.path
            )

            gemini_response: GeminiResponseSchema = get_summary_from_google(
                instance.extracted_text, instance.summary_length
            )
            instance.title = gemini_response.title
            instance.summary = gemini_response.summary
            if request.user.is_authenticated:
                instance.user = request.user
            else:
                uid = self.request.session.get("uid", str(uuid.uuid4()))
                self.request.session["uid"] = uid
                instance.session_uid = uid
            instance.save()

            return JsonResponse(
                SummarySerializer(instance=instance).data, status=HTTP_200_OK
            )
        except ValidationError as e:
            raise DRFValidationError(dict(detail=e))
        except DRFValidationError as e:
            raise e
        except Exception as e:
            raise APIException(e)


class SummaryPageView(TemplateView):
    """
    Sends context data to django template based on uid
    """

    template_name = "llm/summary.html"

    def get_context_data(self, uid, **kwargs):
        ctx = super(SummaryPageView, self).get_context_data(**kwargs)
        ctx["summary"] = get_object_or_404(Summary, uid=uid)
        return ctx

llm/templates/llm/partials/nav.html
<div class="bg-body-tertiary">
  <nav class="container navbar navbar-expand-lg mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'llm:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="navbar-nav gap-3 ms-auto mb-2 mb-lg-0 mt-4 mt-md-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="{% url 'llm:logout' %}">
              Logout
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="{% url 'llm:login' %}">
              Login
            </a>
          </li>
          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'llm:signup' %}">
              Sign Up
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

llm/templates/llm/partials/summary-form.html
<div>
  <div class="fixed-bottom py-3 bg-body mb-0 fixed-bottom d-md-none">
    <div class="container">
      <button class="btn btn-primary w-100" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom">Open Form</button>
    </div>
  </div>

  <div class="offcanvas-md offcanvas-bottom" tabindex="-1" id="offcanvasBottom">
    <form class="form py-4 bg-body mb-0 fixed-bottom" method="post" id="summaryForm" enctype="multipart/form-data">
      <div class="container">
        <div class="row gx-3 gy-4">
          <div class="col-md-5 col-12">
            <label for="attachment" class="form-label d-md-none">Attachment</label>
            <input class="form-control" name="attachment" type="file" id="attachment" accept="application/pdf" required>
            <div id="attachmentError" class="text-danger small mt-2" style="display:none;"></div>
          </div>
          <div class="col-md-5 col-12">
            <label for="summary_length" class="form-label d-md-none">Summary Length</label>
            <select class="form-select" id="summary_length" name="summary_length" required>
              {% for choice in choices.summary_length %}
                <option value="{{ choice.value }}">{{ choice.name }}</option>
              {% endfor %}
            </select>
            <div id="summaryLengthError" class="text-danger small mt-2" style="display:none;"></div>
          </div>
          <div class="col-md-2 col-12">
            {% csrf_token %}
            <button class="btn btn-primary w-100" type="submit" id="submit-btn">
              <span id="submitBtnSpinner" class="spinner-border spinner-border-sm" style="display:none;"></span>
              <span id="submitBtnText" role="status">Submit</span>
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>