litigrit_assessment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("llm-adm/", admin.site.urls),
    re_path(
        r"",
        include(
            ("llm.urls", "llm"),
            namespace="llm",
        ),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

llm/urls.py
from django.urls import path

from llm import views

urlpatterns = [
    path(
        "",
        view=views.HomePageView.as_view(),
        name="home",
    ),
    path(
        "login/",
        view=views.LoginPageView.as_view(),
        name="login",
    ),
    path(
        "signup/",
        view=views.SignupPageView.as_view(),
        name="signup",
    ),
    path(
        "logout/",
        view=views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "summary/",
        view=views.SummaryAPIView.as_view(),
        name="summary",
    ),
    path(
        "summary/<uuid:uid>/",
        view=views.SummaryPageView.as_view(),
        name="summary",
    ),
]

llm/models.py
import uuid

from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db.models import (
    PROTECT,
    CharField,
    DateTimeField,
    FileField,
    ForeignKey,
    Model,
    TextField,
    UUIDField,
)

from llm.taxonomies import SummaryLength


class CreateUpdate(Model):
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Summary(CreateUpdate):
    """
    Model representing a summary generated from a PDF file using the
    Gemini API.

    This model stores extracted text from an uploaded PDF, along with
    a summary and metadata related to the summarization process.
    """

    uid = UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for each summary instance.",
    )
    extracted_text = TextField(
        help_text="Extracted text content from the uploaded PDF file."
    )
    attachment = FileField(
        validators=[FileExtensionValidator(["pdf"])],
        help_text="Only PDF files are allowed for processing.",
    )
    title = CharField(
        max_length=255,
        help_text="Title of the document, generated by the Gemini API.",
    )
    summary = TextField(
        help_text="Summarized content of the extracted text, "
        "generated using the Gemini API."
    )
    summary_length = CharField(
        choices=SummaryLength.choices,
        default=SummaryLength.SHORT,
        help_text="Determines the length of the summary "
        "generated from the Gemini API.",
    )
    user = ForeignKey(
        User,
        on_delete=PROTECT,
        blank=True,
        null=True,
        help_text="Reference to the user who generated "
        "the summary (for logged-in users).",
    )
    session_uid = UUIDField(
        blank=True,
        null=True,
        help_text="Session-based identifier for non-logged-in "
        "users, enabling chat history storage.",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Summaries"

llm/forms.py
# App Imports
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import CharField, Form


class LoginForm(Form):
    username = CharField()
    password = CharField()


class SignupForm(Form):
    """
    Validates if password matchs and if the username is unique or not
    """

    username = CharField()
    password = CharField()
    re_password = CharField()

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if password != re_password:
            raise ValidationError(
                {"re_password": "Passwords doesn't match."}, code="invalid"
            )

        user = User(username=username)
        user.validate_unique()
        user.set_password(raw_password=password)
        user.save()
        self.cleaned_data["user"] = user
        return self.cleaned_data

llm/views.py
import uuid

from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.db.models import Case, F, TextField, Value, When
from django.db.models.functions import Concat, Length, Substr
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView
from rest_framework.exceptions import (
    APIException,
)
from rest_framework.exceptions import ValidationError as DRFValidationError
from rest_framework.status import (
    HTTP_200_OK,
)
from rest_framework.views import APIView

from llm.forms import LoginForm, SignupForm
from llm.gemini import GeminiResponseSchema, get_summary_from_google
from llm.mixins import AuthMixin
from llm.models import Summary
from llm.serializers import SummarySerializer
from llm.utils import extract_text_from_pdf


def is_ajax(request) -> bool:
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


class LoginPageView(FormView):
    """
    Form View to log in the user, this uses django template
    """

    form_class = LoginForm
    template_name = "llm/login.html"
    success_url = reverse_lazy("llm:home")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super(LoginPageView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form: LoginForm):
        user = authenticate(
            self.request,
            username=form.cleaned_data.get("username"),
            password=form.cleaned_data.get("password"),
        )
        if not user:
            form.errors.password = ("Invalid login credentials!!",)
            return super(LoginPageView, self).form_invalid(form)
        login(self.request, user)
        self.request.session["uid"] = None
        return redirect(self.success_url)


class SignupPageView(FormView):
    """
    Form View to sign up the user
    """

    form_class = SignupForm
    template_name = "llm/signup.html"
    success_url = reverse_lazy("llm:home")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super(SignupPageView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form: SignupForm):
        login(self.request, form.cleaned_data["user"])
        self.request.session["uid"] = None
        return redirect(self.success_url)


class LogoutView(AuthMixin, TemplateView):
    """
    View to logout the user if logged in
    """

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse_lazy("llm:home"))


class HomePageView(TemplateView):
    template_name = "llm/home.html"

    def get_context_data(self, **kwargs):
        """
        Fetches chat history based on user's login status.

        Reduces the extracted text length to 300 for optimized
        list view using django ORM's annotate
        """
        ctx = super(HomePageView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            filters = dict(user__id=self.request.user.id)
        elif uid := self.request.session.get("uid"):
            filters = dict(session_uid=uid)
        else:
            filters = dict(uid=None)
        ctx["history"] = (
            Summary.objects.filter(**filters)
            .annotate(
                extracted_text_length=Length("extracted_text"),
                short_extracted_text=Case(
                    When(
                        extracted_text_length__gt=300,
                        then=Concat(
                            Substr("extracted_text", 1, 300), Value("...")
                        ),
                    ),
                    default=F("extracted_text"),
                    output_field=TextField(),
                ),
            )
            .values(
                "uid",
                "created",
                "title",
                "summary",
                "short_extracted_text",
                "attachment",
            )
            .order_by("created")
        )
        return ctx


class SummaryAPIView(APIView):
    """
    Summary post using DRF, we can also use FormView but I wanted to showcase
    DRF skills. It assign values to Summary instance which we fetch data
    from gemini and populates user and session_uid.
    """

    def post(self, request, *args, **kwargs):
        try:
            serializer = SummarySerializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            instance: Summary = serializer.save()

            instance.extracted_text = extract_text_from_pdf(
                instance.attachment.path
            )

            gemini_response: GeminiResponseSchema = get_summary_from_google(
                instance.extracted_text, instance.summary_length
            )
            instance.title = gemini_response.title
            instance.summary = gemini_response.summary
            if request.user.is_authenticated:
                instance.user = request.user
            else:
                uid = self.request.session.get("uid", str(uuid.uuid4()))
                self.request.session["uid"] = uid
                instance.session_uid = uid
            instance.save()

            return JsonResponse(
                SummarySerializer(instance=instance).data, status=HTTP_200_OK
            )
        except ValidationError as e:
            raise DRFValidationError(dict(detail=e))
        except DRFValidationError as e:
            raise e
        except Exception as e:
            raise APIException(e)


class SummaryPageView(TemplateView):
    """
    Sends context data to django template based on uid
    """

    template_name = "llm/summary.html"

    def get_context_data(self, uid, **kwargs):
        ctx = super(SummaryPageView, self).get_context_data(**kwargs)
        ctx["summary"] = get_object_or_404(Summary, uid=uid)
        return ctx

llm/templates/llm/base.html
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  {% block extra_head %}{% endblock extra_head %}
  {% block head_script %}{% endblock head_script %}
  <title>
    {% block title %}
      Content Summary from PDF
    {% endblock title %}
  </title>
</head>

<body data-bs-theme="dark">
  {% csrf_token %}

  {% include 'llm/partials/nav.html' %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <div class="toast-container position-fixed top-0 start-50 translate-middle-x p-3">
    <div id="errorToast" class="toast bg-danger-subtle" role="alert">
      <div class="toast-body" id="message">
      </div>
    </div>
  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}" type="module"></script>

  {% block script %}{% endblock script %}
</body>
</html>

llm/templates/llm/home.html
{% extends 'llm/base.html' %}
{% load static markdownify %}

{% block content %}
{% if history.count == 0 %}
  <div class="position-absolute w-100 top-50 start-50 translate-middle text-center">
    <div class="container">
      <div class="card max-w-400 text-center mx-auto">
        <div class="card-header display-6 fw-bold">
          PDF Summary
        </div>
        <div class="card-body">
          <p class="card-text">
            A web app that quickly extracts and summarizes text from PDF files using the Gemini LLM API. Designed for efficiency, it helps users save time by turning long documents into concise, easy-to-read summaries. Built with Django, PostgreSQL, and a sleek Bootstrap frontend, it is the perfect tool for professionals and students who need fast insights from PDFs.
          </p>
        </div>
        <div class="card-footer">
          <p class="h5">
            Upload to see History!
          </p>
        </div>
      </div>
    </div>
  </div>
{% else %}
  <ul id="history" class="list-unstyled my-5">
    {% for summary in history %}
    <li class="d-flex justify-content-end mb-4">
      <div class="card shadow chat-box">
        <div class="card-header fw-bold">
          {{ summary.attachment }}
        </div>
        <div class="card-body">
          <p class="card-text mb-3">{{ summary.short_extracted_text|markdownify }}</p>
          <a href="{% url 'llm:summary' summary.uid %}" class="btn btn-sm btn-outline-primary">Get Full Info</a>
        </div>
        <div class="card-footer">
          <p class="small mb-0">{{ summary.created }}</p>
        </div>
      </div>
    </li>
    <li class="d-flex justify-content-start mb-4">
      <div class="card shadow chat-box">
        <div class="card-header fw-bold">
          {{ summary.title }}
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ summary.summary|markdownify }}
          </p>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
  <div class="pb-5"></div>
{% endif %}

{% include 'llm/partials/summary-form.html' %}

{% endblock content %}

llm/templates/llm/login.html
{% extends "llm/base.html" %}
{% load static %}

{% block content %}
<div class="position-absolute top-50 start-50 translate-middle w-100">
  <div class="container">
    <div class="card mx-auto shadow max-w-400 p-5">
      <h1 class="text-center mb-5">Login</h1>
      <form method="POST" class="form" id="loginForm">
        <div class="form-group mb-4">
          <label for="username" class="form-label">Username</label>
          <input type="text" name="username" id="username" class="form-control w-100" placeholder="Username" autofocus required>
          {% if form.errors.username %}
            <div class="small text-danger mt-2">{{ form.errors.username|join:' ' }}</div>
          {% endif %}
        </div>
        <div class="form-group mb-4">
          <label for="password" class="form-label">Password</label>
          <input type="password" name="password" id="password" class="form-control w-100" placeholder="Password" required>
          {% if form.errors.password %}
            <div class="small text-danger mt-2">{{ form.errors.password|join:' ' }}</div>
          {% endif %}
        </div>
        {% if form.errors.all %}
          <div class="alert alert-danger mt-2">{{ form.errors.all|join:' ' }}</div>
        {% endif %}
        <div>
          {% csrf_token %}
          <button class="btn btn-primary w-100" type="submit" id="login-btn">
            <span id="loginBtnSpinner" class="spinner-border spinner-border-sm" style="display:none;"></span>
            <span id="loginBtnText" role="status">Login</span>
          </button>
        </div>
      </form>
      <hr>
      <a class="btn btn-outline-primary mt-3" href="{% url 'llm:signup' %}">
        Sign Up Instead
      </a>
    </div>
</div>
</div>
{% endblock content %}

{% block script %}
  <script>
    $('#loginForm').on('submit', function(e) {
      $("#loginForm button").prop("disabled", true);
      $('#loginBtnSpinner').show();
      $('#loginBtnText').text("Loading");

      e.preventDefault();
      e.target.submit();
    });
  </script>
{% endblock script %}

llm/templates/llm/signup.html
{% extends "llm/base.html" %}
{% load static %}

{% block content %}
<div class="position-absolute top-50 start-50 translate-middle w-100">
  <div class="container">
    <div class="card mx-auto shadow max-w-400 p-5">
      <h1 class="text-center mb-5">Signup</h1>
      <form method="POST" class="form" id="signupForm">
        <div class="form-group mb-4">
          <label for="username" class="form-label">Username</label>
          <input type="text" name="username" id="username" class="form-control w-100" placeholder="Username" autofocus required>
          {% if form.errors.username %}
            <div class="small text-danger mt-2">{{ form.errors.username|join:' ' }}</div>
          {% endif %}
        </div>
        <div class="form-group mb-4">
          <label for="password" class="form-label">Password</label>
          <input type="password" name="password" id="password" class="form-control w-100" placeholder="Password" required>
          {% if form.errors.password %}
            <div class="small text-danger mt-2">{{ form.errors.password|join:' ' }}</div>
          {% endif %}
        </div>
        <div class="form-group mb-4">
          <label for="re_password" class="form-label">Password Again</label>
          <input type="password" name="re_password" id="re_password" class="form-control w-100" placeholder="Password Again" required>
          {% if form.errors.re_password %}
            <div class="small text-danger mt-2">{{ form.errors.re_password|join:' ' }}</div>
          {% endif %}
        </div>
        {% if form.errors.all %}
          <div class="alert alert-danger mt-2">{{ form.errors.all|join:' ' }}</div>
        {% endif %}
        <div>
          {% csrf_token %}
          <button class="btn btn-primary w-100" type="submit" id="signup-btn">
            <span id="signupBtnSpinner" class="spinner-border spinner-border-sm" style="display:none;"></span>
            <span id="signupBtnText" role="status">Sign Up</span>
          </button>
        </div>
      </form>
      <hr>
      <a class="btn btn-outline-primary mt-3" href="{% url 'llm:login' %}">
        Login Instead
      </a>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script>
  $('#signupForm').on('submit', function(e) {
    $("#signupForm button").prop("disabled", true);
    $('#signupBtnSpinner').show();
    $('#signupBtnText').text("Loading");

    e.preventDefault();
    e.target.submit();
  });
</script>
{% endblock script %}

llm/templates/llm/summary.html
{% extends 'llm/base.html' %}
{% load static markdownify %}

{% block title %}
  {{ summary.title }}
{% endblock title %}

{% block content %}
<div class="mt-5">
  <nav style="--bs-breadcrumb-divider: '>';" class="mb-5">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'llm:home' %}">Home</a></li>
      <li class="breadcrumb-item active">{{ summary.title }}</li>
    </ol>
  </nav>
  <div class="mb-5 text-center">
    <h4 class="display-6 fw-bold">
     {{ summary.title }}
    </h4>
    <p class="small mb-3">{{ summary.created }}</p>
    <a href="{{ summary.attachment.url }}" target="_blank" rel="noopener noreferrer">View File</a>
  </div>

  <div class="mb-5">
    <h5 class="fw-bold mb-3">Summary</h5>
    <div class="lh-lg">{{ summary.summary|markdownify }}</div>
  </div>
  <div class="mb-5">
    <h5 class="fw-bold mb-3">Extracted Text</h5>
    <div class="lh-lg">{{ summary.extracted_text|markdownify }}</div>
  </div>
  <div class="pb-5"></div>
  {% include 'llm/partials/summary-form.html' %}
</div>
{% endblock content %}